apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-proxy-service
  namespace: redis
  labels:
    app: redis-sentinel-proxy-service
spec:
  type: NodePort
  ports:
    - port: 6379
      name: redis-sentinel-proxy-service
  selector:
    app: redis-sentinel-proxy-service
