apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis-sentinel-proxy-service
  namespace: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-sentinel-proxy-service
    spec:
      containers:
        - name: redis-sentinel-proxy-service
          image: mobilefzb/redis-sentinel-proxy-service:latest
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - "-listen"
            - "0.0.0.0:6379"
            - "-master"
            - "mymaster"
            - "-sentinel"
            - "redis-sentinel-0:26379,redis-sentinel-1:26379,redis-sentinel-2:26379"
          ports:
            - containerPort: 6379
