apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis-sentinel-proxy-service
  namespace: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-sentinel-proxy-service
    spec:
      containers:
        - name: redis-sentinel-proxy-service
          image: mobilefzb/redis-sentinel-proxy-service:latest
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - "-master"
            - "primary"
            - "-sentinel"
            - "redis-sentinel.$(NAMESPACE):26379"
          ports:
            - containerPort: 9999
